// src/constants/freelancerConstants.js

export const FREELANCERS_LIST_REQUEST = 'FREELANCERS_LIST_REQUEST';
export const FREELANCERS_LIST_SUCCESS = 'FREELANCERS_LIST_SUCCESS';
export const FREELANCERS_LIST_FAIL = 'FREELANCERS_LIST_FAIL';

export const FREELANCERS_FILTER_BY_RATING = 'FREELANCERS_FILTER_BY_RATING';
export const FREELANCERS_FILTER_BY_PROJECTS = 'FREELANCERS_FILTER_BY_PROJECTS';
