// constants/taskConstants.js
export const MILESTONE_LIST_REQUEST = 'MILESTONE_LIST_REQUEST';
export const MILESTONE_LIST_SUCCESS = 'MILESTONE_LIST_SUCCESS';
export const MILESTONE_LIST_FAIL = 'MILESTONE_LIST_FAIL';

// constants/milestoneConstants.js
export const MILESTONE_STATS_REQUEST = 'MILESTONE_STATS_REQUEST';
export const MILESTONE_STATS_SUCCESS = 'MILESTONE_STATS_SUCCESS';
export const MILESTONE_STATS_FAIL = 'MILESTONE_STATS_FAIL';

export const MILESTONE_CREATE_REQUEST = "MILESTONE_CREATE_REQUEST";
export const MILESTONE_CREATE_SUCCESS = "MILESTONE_CREATE_SUCCESS";
export const MILESTONE_CREATE_FAIL = "MILESTONE_CREATE_FAIL";
