//Constants for the product detail page.

export const PROJECT_DETAILS_REQUEST = 'PROJECT_DETAILS_REQUEST'
export const PROJECT_DETAILS_SUCCESS= 'PROJECT_DETAILS_SUCCESS'
export const PROJECT_DETAILS_FAIL = 'PROJECT_DETAILS_FAIL'


export const IS_PROJECT_OWNER_REQUEST= 'IS_PROJECT_OWNER_REQUEST'
export const IS_PROJECT_OWNER_SUCCESS = 'IS_PROJECT_OWNER_SUCCESS'
export const IS_PROJECT_OWNER_FAIL = 'IS_PROJECT_OWNER_FAIL'

export const PROJECT_OFFER_REQUEST = 'PROJECT_OFFER_REQUEST';
export const PROJECT_OFFER_SUCCESS = 'PROJECT_OFFER_SUCCESS';
export const PROJECT_OFFER_FAIL = 'PROJECT_OFFER_FAIL';

export const PROJECT_LIST_REQUEST = 'PROJECT_LIST_REQUEST';
export const PROJECT_LIST_SUCCESS = 'PROJECT_LIST_SUCCESS';
export const PROJECT_LIST_FAIL = 'PROJECT_LIST_FAIL';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';
export const PROJECT_CREATE_RESET = 'PROJECT_CREATE_RESET';

export const PROJECT_OWNED_LIST_REQUEST = 'PROJECT_OWNED_LIST_REQUEST';
export const PROJECT_OWNED_LIST_SUCCESS = 'PROJECT_OWNED_LIST_SUCCESS';
export const PROJECT_OWNED_LIST_FAIL = 'PROJECT_OWNED_LIST_FAIL';

export const PROJECT_WORKING_LIST_REQUEST = 'PROJECT_WORKING_LIST_REQUEST';
export const PROJECT_WORKING_LIST_SUCCESS = 'PROJECT_WORKING_LIST_SUCCESS';
export const PROJECT_WORKING_LIST_FAIL = 'PROJECT_WORKING_LIST_FAIL';

export const PROJECT_COMMENTS_REQUEST = 'PROJECT_COMMENTS_REQUEST';
export const PROJECT_COMMENTS_SUCCESS = 'PROJECT_COMMENTS_SUCCESS';
export const PROJECT_COMMENTS_FAIL = 'PROJECT_COMMENTS_FAIL';

export const MILESTONE_COMMENTS_REQUEST = 'MILESTONE_COMMENTS_REQUEST';
export const MILESTONE_COMMENTS_SUCCESS = 'MILESTONE_COMMENTS_SUCCESS';
export const MILESTONE_COMMENTS_FAIL = 'MILESTONE_COMMENTS_FAIL';

export const TASK_COMMENTS_REQUEST = 'TASK_COMMENTS_REQUEST';
export const TASK_COMMENTS_SUCCESS = 'TASK_COMMENTS_SUCCESS';
export const TASK_COMMENTS_FAIL = 'TASK_COMMENTS_FAIL';

export const ADD_TASK_COMMENT_REQUEST = 'ADD_TASK_COMMENT_REQUEST'
export const ADD_TASK_COMMENT_SUCCESS = 'ADD_TASK_COMMENT_SUCCESS'
export const ADD_TASK_COMMENT_FAIL = 'ADD_TASK_COMMENT_FAIL';

export const ADD_MILESTONE_COMMENT_FAIL = 'ADD_MILESTONE_COMMENT_FAIL';
export const ADD_MILESTONE_COMMENT_REQUEST = 'ADD_MILESTONE_COMMENT_REQUEST';
export const ADD_MILESTONE_COMMENT_SUCCESS = 'ADD_MILESTONE_COMMENT_SUCCESS';

export const ADD_PROJECT_COMMENT_SUCCESS = 'ADD_PROJECT_COMMENT_SUCCESS';
export const ADD_PROJECT_COMMENT_REQUEST = 'ADD_PROJECT_COMMENT_REQUEST';
export const ADD_PROJECT_COMMENT_FAIL = 'ADD_PROJECT_COMMENT_FAIL';

