// constants/taskConstants.js
export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL';

export const TASK_CREATE_REQUEST='TASK_CREATE_REQUEST';
export const TASK_CREATE_SUCCESS='TASK_CREATE_SUCCESS';
export const TASK_CREATE_FAIL='TASK_CREATE_FAIL';

// constants/taskConstants.js
export const TASK_STATS_REQUEST = 'TASK_STATS_REQUEST';
export const TASK_STATS_SUCCESS = 'TASK_STATS_SUCCESS';
export const TASK_STATS_FAIL = 'TASK_STATS_FAIL';