# Generated by Django 4.2.8 on 2024-11-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='NameBill')),
                ('task_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='TaskPrice')),
                ('status_changed_at', models.DateTimeField(auto_now=True, verbose_name='ChangeStatusDate')),
            ],
        ),
    ]
