# Generated by Django 4.2.8 on 2024-11-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='projects.milestone', verbose_name='LinkedMilestone'),
        ),
        migrations.AddField(
            model_name='bill',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='projects.project', verbose_name='LinkedProject'),
        ),
        migrations.AddField(
            model_name='bill',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='projects.task', verbose_name='LinkedTask'),
        ),
    ]
