# Generated by Django 4.2.8 on 2024-11-17 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='bills_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
